name: cassiere
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^6.0.7096
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  uuid: ^3.0.7
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2
  flutter_svg: ^1.1.6
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  hive: ^2.2.3
  qr_flutter: ^4.0.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  flutter_riverpod: ^2.1.1
  mobile_scanner: ^2.1.0
  carousel_slider: ^4.2.1
  flutter_map: ^3.0.0
  geolocator: ^9.0.2
  badges: ^2.0.3
  faker_dart: ^0.1.11
  firebase_storage: ^11.0.8
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
